### ISSUE TITLE
can't register to Polar Cloud

### ISSUE THREAD

**Issue by gdachs** [nunofgs/rpi-octoprint#17]
I get this error message if I try to register to PolarCloud:
`
2019-05-11 20:10:53,852 - octoprint.plugins.polarcloud - ERROR - Failed to run system command: ssh-keygen -e -m PEM -f /data/data/polarcloud/p3d_key > /data/data/polarcloud/p3d_key.pub
Traceback (most recent call last):
  File "/data/plugins/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 291, in _system
    p = sarge.run(command_line, stderr=sarge.Capture())
  File "/usr/local/lib/python2.7/site-packages/octoprint/util/fixes.py", line 24, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sarge/__init__.py", line 1462, in run
    p.run(input=input, async_=async_)
  File "/usr/local/lib/python2.7/site-packages/sarge/__init__.py", line 156, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/site-packages/sarge/__init__.py", line 1150, in close
    stream.close()
IOError: [Errno 9] Bad file descriptor
`
The [Readme](https://github.com/markwal/OctoPrint-PolarCloud/blob/master/README.md#note-for-users-running-octoprint-on-windows) is referring to an older version of pyOpenSSL on Windows, not very helpful.

What would be the right way to investigate and fix this?

**Comment by gdachs** [comment]
Is it just as easy as adding openssh-client to the dependencies in the Dockerfile?

**Comment by gdachs** [comment]
I used the console of the container and installed openssh-client and I can register to Polar Cloud.
As this is a one time job, there is no problem that your next image will overwrite it.

**Comment by nunofgs** [comment]
@gdachs FWIW I don't see a problem with adding openssh-client. Adds a little bit of size to the image but worth it in this case. It should be available on Docker hub momentarily.
