### ISSUE TITLE
Updating to 1.4.2 on alpine doesn't work

### ISSUE THREAD

**Issue by gshlomi** [nunofgs/rpi-octoprint#43]
Updating, please wait.
/usr/local/bin/python -m pip --disable-pip-version-check install https://github.com/foosel/OctoPrint/archive/1.4.2.zip --no-cache-dir
Collecting https://github.com/foosel/OctoPrint/archive/1.4.2.zip
Downloading https://github.com/foosel/OctoPrint/archive/1.4.2.zip (5.4 MB)
Collecting OctoPrint-FirmwareCheck>=2020.06.22
Downloading OctoPrint_FirmwareCheck-2020.6.22-py2.py3-none-any.whl (26 kB)
Collecting OctoPrint-FileCheck>=2020.07.06
Downloading OctoPrint_FileCheck-2020.8.7-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.1.1)
Collecting tornado==5.1.1
Downloading tornado-5.1.1.tar.gz (516 kB)
Requirement already satisfied: markdown<3.2,>=3.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (3.1.1)
Requirement already satisfied: rsa==4.0 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (4.0)
Requirement already satisfied: regex!=2018.11.6 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (2020.2.20)
Collecting flask<2,>=1.1.2
Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Jinja2<3,>=2.11.2
Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting Flask-Login<0.6,>=0.5
Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
Collecting Flask-Babel<2,>=1.0
Downloading Flask-Babel-1.0.0.tar.gz (49 kB)
Collecting Flask-Assets<3,>=2.0
Downloading Flask-Assets-2.0.tar.gz (23 kB)
Collecting werkzeug<2,>=1.0.1
Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.1.0)
Requirement already satisfied: cachelib<1,>=0.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.1)
Collecting PyYAML<6,>=5.3.1
Downloading PyYAML-5.3.1.tar.gz (269 kB)
Requirement already satisfied: pyserial<4,>=3.4 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (3.4)
Requirement already satisfied: netaddr<1,>=0.7.19 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.7.19)
Collecting watchdog<1,>=0.10.2
Downloading watchdog-0.10.3.tar.gz (94 kB)
Requirement already satisfied: sarge==0.1.5post0 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.1.5.post0)
Requirement already satisfied: netifaces<1,>=0.10.9 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.10.9)
Requirement already satisfied: pylru<2,>=1.2 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.2.0)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.5.0.1)
Requirement already satisfied: requests<3,>=2.23.0 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (2.23.0)
Collecting semantic_version<3,>=2.8.5
Downloading semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting psutil<6,>=5.7
Downloading psutil-5.7.2.tar.gz (460 kB)
Collecting Click<8,>=7.1.2
Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: feedparser<6,>=5.2.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (5.2.1)
Requirement already satisfied: future<1,>=0.18.2 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.18.2)
Collecting websocket-client<1,>=0.57
Downloading websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting wrapt<2,>=1.12.1
Downloading wrapt-1.12.1.tar.gz (27 kB)
Requirement already satisfied: emoji<1,>=0.5.4 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.5.4)
Requirement already satisfied: frozendict<2,>=1.2 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.2)
Collecting sentry-sdk<1,>=0.15.1
Downloading sentry_sdk-0.16.3-py2.py3-none-any.whl (110 kB)
Collecting filetype<2,>=1.0.7
Downloading filetype-1.0.7-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (0.4.21)
Requirement already satisfied: blinker<2,>=1.4 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.4)
Requirement already satisfied: futures<4,>=3.3 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (3.3.0)
Requirement already satisfied: monotonic<2,>=1.5 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.5)
Requirement already satisfied: scandir<2,>=1.10 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.10.0)
Requirement already satisfied: chainmap<2,>=1.0.3 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (1.0.3)
Requirement already satisfied: typing<4,>=3.7.4.1 in /usr/local/lib/python2.7/site-packages (from OctoPrint==1.4.2) (3.7.4.1)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint==1.4.2) (3.4.0.3)
Requirement already satisfied: backports_abc>=0.4 in /usr/local/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint==1.4.2) (0.5)
Requirement already satisfied: setuptools>=36 in /usr/local/lib/python2.7/site-packages (from markdown<3.2,>=3.1->OctoPrint==1.4.2) (44.0.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/site-packages (from rsa==4.0->OctoPrint==1.4.2) (0.4.8)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint==1.4.2) (2019.3)
Requirement already satisfied: Babel>=2.3 in /usr/local/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint==1.4.2) (2.8.0)
Requirement already satisfied: webassets>=2.0 in /usr/local/lib/python2.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint==1.4.2) (2.0)
Requirement already satisfied: pathtools>=0.1.1 in /usr/local/lib/python2.7/site-packages (from watchdog<1,>=0.10.2->OctoPrint==1.4.2) (0.1.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint==1.4.2) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint==1.4.2) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint==1.4.2) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint==1.4.2) (2019.11.28)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from websocket-client<1,>=0.57->OctoPrint==1.4.2) (1.14.0)
Building wheels for collected packages: OctoPrint, tornado, Flask-Babel, Flask-Assets, PyYAML, watchdog, psutil, wrapt
Building wheel for OctoPrint (setup.py): started
Building wheel for OctoPrint (setup.py): finished with status 'done'
Created wheel for OctoPrint: filename=OctoPrint-1.4.2-py2.py3-none-any.whl size=2860990 sha256=bb9369a837f7525338463a6baf0eabae3789fdbfb74277cc2c6adcc586dda8e6
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/20/b4/8a/d6a782b3c57cfb7ac8f3a2b41158e055c11f05fb139d58d35d
Building wheel for tornado (setup.py): started
Building wheel for tornado (setup.py): finished with status 'done'
Created wheel for tornado: filename=tornado-5.1.1-cp27-cp27mu-linux_x86_64.whl size=460935 sha256=5e2d36351f3fc482038896572721e6b6e7956f7cd71d688c02413689af97bb98
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/d8/83/af/e0dc6afbf3a2c51af8d6e3f9fbe790d0c581c2de05bc5d50f5
Building wheel for Flask-Babel (setup.py): started
Building wheel for Flask-Babel (setup.py): finished with status 'done'
Created wheel for Flask-Babel: filename=Flask_Babel-1.0.0-py2-none-any.whl size=9496 sha256=5e8419911da427a8ee4077bc3aa302a59d39559ff5497d1e53fa8b5bcc228c66
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/dc/7a/67/9627e7437139ed84192412c0f6466cc87e4f3e69aceb3aa59d
Building wheel for Flask-Assets (setup.py): started
Building wheel for Flask-Assets (setup.py): finished with status 'done'
Created wheel for Flask-Assets: filename=Flask_Assets-2.0-py2-none-any.whl size=8450 sha256=f94b810668f78b090374e54bfbcfe258ca5dbf71e6b4b46476a97daeb9c44b80
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/35/8b/cb/826c670975afca83017a3c128b988d58439427fff7229d6499
Building wheel for PyYAML (setup.py): started
Building wheel for PyYAML (setup.py): finished with status 'done'
Created wheel for PyYAML: filename=PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl size=45644 sha256=6b30c9ae429a595632ff07ea0ae1964cc600c39af08f9db77082c2015c67279b
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2
Building wheel for watchdog (setup.py): started
Building wheel for watchdog (setup.py): finished with status 'done'
Created wheel for watchdog: filename=watchdog-0.10.3-py2-none-any.whl size=73870 sha256=a1c612cac82e7a8e41db06d2ba4a3d74c969820fcc18e3766be9060d43cd25c2
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/ce/11/7a/61f71c3e64ee3bf11134304f5fa9dfc0b523a95a7b3cfbe476
Building wheel for psutil (setup.py): started
Building wheel for psutil (setup.py): finished with status 'error'
Running setup.py clean for psutil
Building wheel for wrapt (setup.py): started
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-GlleWT
cwd: /tmp/pip-install-FR2uX1/psutil/
Complete output (50 lines):
/tmp/tmppxb3ug.c:1:10: fatal error: linux/ethtool.h: No such file or directory
#include <linux/ethtool.h>
^~~~~~~~~~~~~~~~~
compilation terminated.
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/psutil
copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
creating build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/runner.py -> build/lib.linux-x86_64-2.7/psutil/tests
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/psutil
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/local/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/local/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o
psutil/_psutil_posix.c:29:14: fatal error: linux/types.h: No such file or directory
#include <linux/types.h>
^~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for psutil
Building wheel for wrapt (setup.py): finished with status 'done'
Created wheel for wrapt: filename=wrapt-1.12.1-cp27-cp27mu-linux_x86_64.whl size=70598 sha256=99006f8ae105555a36b074316a91217d952acfe7962ab8d433b36fa834bc1e79
Stored in directory: /tmp/pip-ephem-wheel-cache-cTZblM/wheels/5b/d8/8e/81a83cb5321b940a954996f5b57fddc8976e712b3ac3a1a54b
Successfully built OctoPrint tornado Flask-Babel Flask-Assets PyYAML watchdog wrapt
Failed to build psutil
Installing collected packages: OctoPrint-FirmwareCheck, OctoPrint-FileCheck, tornado, werkzeug, Click, Jinja2, flask, Flask-Login, Flask-Babel, Flask-Assets, PyYAML, watchdog, semantic-version, psutil, websocket-client, wrapt, sentry-sdk, filetype, OctoPrint
WARNING: The script flask is installed in '/data/plugins/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script watchmedo is installed in '/data/plugins/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ie87W1/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /data/plugins/include/python2.7/psutil
cwd: /tmp/pip-install-FR2uX1/psutil/
Complete output (50 lines):
/tmp/tmpi1t4H4.c:1:10: fatal error: linux/ethtool.h: No such file or directory
#include <linux/ethtool.h>
^~~~~~~~~~~~~~~~~
compilation terminated.
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/psutil
copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
creating build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
copying psutil/tests/runner.py -> build/lib.linux-x86_64-2.7/psutil/tests
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/psutil
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/local/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/local/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o
psutil/_psutil_posix.c:29:14: fatal error: linux/types.h: No such file or directory
#include <linux/types.h>
^~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FR2uX1/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ie87W1/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /data/plugins/include/python2.7/psutil Check the logs for full command output.
Running setup.py install for psutil: started
Running setup.py install for psutil: finished with status 'error'
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by gshlomi** [comment]
[octoprint.log](https://github.com/nunofgs/docker-octoprint/files/5046211/octoprint.log)
[plugin_softwareupdate_console.log](https://github.com/nunofgs/docker-octoprint/files/5046212/plugin_softwareupdate_console.log)

**Comment by SckyzO** [comment]
For update Octoprint, please only use docker pull. Currently, Nunofgs not push this version.  Please wait. Do not use internal mechanism for update octoprint. Docker doesn't work like this !  :)

**Comment by ertraid** [comment]
Wished I had seen this before!
Unfortunatelly I upgraded to 1.4.2 using Octoprint mechanism... The upgraded ended well, but now the container will not start... any suggestion on how to undo my mess?

Container log (in a constant loop):

2020-08-21 14:14:59,425 INFO spawned: 'octoprint' with pid 113

2020-08-21 14:15:00,428 INFO success: octoprint entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Traceback (most recent call last):

  File "/usr/local/bin/octoprint", line 11, in <module>

    load_entry_point('OctoPrint==1.4.0', 'console_scripts', 'octoprint')()

  File "/usr/local/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint/__init__.py", line 614, in main

    from octoprint.cli import octo

  File "/usr/local/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint/cli/__init__.py", line 138, in <module>

    from .client import client_commands

  File "/usr/local/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint/cli/client.py", line 13, in <module>

    import octoprint_client

  File "/usr/local/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint_client/__init__.py", line 8, in <module>

    import requests

  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>

    import urllib3

  File "/usr/local/lib/python2.7/site-packages/urllib3/__init__.py", line 21, in <module>

    from logging import NullHandler

ImportError: cannot import name NullHandler

2020-08-21 14:15:00,960 INFO exited: octoprint (exit status 1; not expected)

**Comment by tg44** [comment]
if you have the same problem;
cd your `data/plugins/lib/python2.7/site-packages` and run;
```

rm -rf Flask*
rm -rf flask*
rm -rf Jinja2-2.11.2.dist-info/
rm -rf jinja2/
rm -rf octoprint_client/
rm -rf OctoPrint_FileCheck-2020.8.7.dist-info/
rm -rf octoprint_file_check/
rm -rf OctoPrint_FirmwareCheck-2020.6.22.dist-info/
rm -rf octoprint_firmware_check/
rm -rf octoprint_setuptools/
rm -rf psutil*
rm -rf PyYAML-5.3.1.dist-info/
rm -rf semantic_version*
rm -rf sentry_sdk*
rm -rf tornado*
rm -rf websocket*
rm -rf watchdog*
rm -rf werkzeug/
rm -rf Werkzeug-1.0.1.dist-info/
rm -rf wrapt*
rm -rf yaml/
rm -rf OctoPrint-1.4.2.dist-info/
rm -rf octoprint
```

Ofc. this can mess up other plugins, but at least after this my 1.4.0 instance is started without a noteable dataloss...

**Comment by SckyzO** [comment]
Or just delete your container, move your data folder (for backup), and restart it.

**Comment by tg44** [comment]
That will not really work... as you see the data folder has the plugins in it. The problem is bcs the octoprint 1.4.0 (which called directly from the bin) starts to use the new flask folder (I didn't check, but I think the original container has a flask folder in it too), which is not compatible anymore (it would be compatible with the 1.4.2, but the bin still calls the 1.4.0 after the upgrade)... 

So simply moving the data folder will keep the container in a die loop. Not moving the plugins folder will leave you without your plugins. The only "good" solution is either starting and configuring a new container with an empty data folder, or rolling back the plugins to the state before the upgrade to 1.4.2. I provided the list of touched/new folders and how to remove them to the second way.

The best option is still simply not to click to the octoprint version update on the ui :D



EDIT; for clarification, just delete and start the same container not worked. Not the container inner state infected, but the container inner state + plugins folder went to a "not working" state together, so simply dropping the container will not solve anything, you need to patch the plugins folder too.

**Comment by ertraid** [comment]
I am currently out of town, but will try tg44's suggested patching when I get back... not sure I clarified, but I am on Raspbian.. hope the suggested patches are the same?

BTW, recreating a new container with the same old data folder does not work.. had tried that before posting… endless loop as per my original post.

Also, any idea when we could see a 1.4.2 image here? That should fix it, and might be worth waiting if tg44's suggestion fails to work.

As for the best option suggested..sure thing.. learned my lesson now!

ET

**Comment by ertraid** [comment]
Update: just completed all the edits (deletions) suggested by tg44 above and launched a new container mapping to the modified /data... Back to working 1.4.0! 
I had 10+ plugins installed and all seems to work for now... Thanks much!
Will never upgrade again using the OctoPrint UI. I promise.! =)
